### ISSUE TITLE
Is project alive ?

### ISSUE THREAD

**Issue by jmanteau** [terryli710/Obsidian-TaskCard#65]
This project seems quite interesting for task management. However before investing time in it, I would like to know if the version 1.0 will happen someday ? 
Or does the author doesn't have time to finish it ?
The current version is great anyway.

**Comment by terryli710** [comment]
Thank you for your interest in this plugin! I appreciate your support.

This project has been a side endeavor that I work on during my free time. While I haven't been actively developing it recently due to other commitments, I've had some new ideas and have just picked it up again recently. Although my main work and other responsibilities keep me pretty busy, I still plan to continue developing this plugin, even if progress might be slow.

Version 1.0 will be released eventually, though not in the immediate future. I encourage you to stay tuned to the repository for updates, as I'll be posting new versions as they become available.
